ProjectManagerWeb/ProjectManagerNew/Controllers/AssigmentController.cs
using AutoMapper;
using BLL.Interfaces;
using Core.Models;
using Core.ViewModels;
using Core.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ProjectManagerNew.Controllers
{
    [Authorize]
    public class AssigmentController : Controller
    {
        private readonly IAssigmentService _assigmentService;
        private readonly IUserAuthenticationService _userAuthenticationService;
        private readonly UserManager<AppUser> _userManager;
		public AssigmentController(IAssigmentService assigmentService,
            IUserAuthenticationService userAuthenticationService,
            UserManager<AppUser> userManager)
        {
            _assigmentService = assigmentService;
            _userAuthenticationService = userAuthenticationService;
            _userManager = userManager;
		}
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [Route("Create/{id}")]
        public async Task<IActionResult> Create(Guid id)
        {
            var assigmentVM = new AssigmentCreateViewModel() { CurrentProjectId = id };

            var users = await _userAuthenticationService.GetUsersForTaskCompliting();
            var userCheckboxes = new List<AppUserCheckBoxViewModel>();
            foreach (var user in users)
            {
                var checkbox = new AppUserCheckBoxViewModel
                {
                    IsActive = false,
                    Description = $"{user.UserName} - {user.Email} ",
                    Value = user
                };

                userCheckboxes.Add(checkbox);
            }

            assigmentVM.ResponsibleUsersCheckboxes = userCheckboxes;

            return View(assigmentVM);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAssigment(AssigmentCreateViewModel model)
        {
            if (!ModelState.IsValid) 
                return View("Create", model);

            var config = new MapperConfiguration(cfg => cfg.CreateMap<AssigmentCreateViewModel, Assigment>());
            var mapper = new Mapper(config);
            var assigment = mapper.Map<Assigment>(model);

            var result = await _assigmentService.CreateAssigment(assigment, model.ResponsibleUsers);

            if(!result.IsSuccessful)
                TempData["Error"] = result.Message;

            return RedirectToAction("Details", "Project");
        }

        [HttpGet]
		[Route("ShowProjectTasks/{id}")]
		public async Task<IActionResult> ShowProjectTasks(Guid id)
        {
            var projectTasks = await _assigmentService.GetAllProjectTasks(id);
            var sortedAssigments = projectTasks.SortAssigmentsByPriority();

            return View(sortedAssigments);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var assigment = await _assigmentService.GetById(id);

            if (assigment == null)
                return View("Error");

            var assigmentVM = new AssigmentDeleteViewModel()
            {
                AssigmentId = id,
                AssigmentName = assigment.Name,
                ProjectName = assigment.AssigmentProject.Name
            };

            return View(assigmentVM);
        }

        [HttpGet]
        [Route("DeleteTask/{id}")]
        public async Task<IActionResult> DeleteTask(Guid id)
        {
            var assigment = await _assigmentService.GetById(id);

            if(assigment == null)
                return View("Error");

            await _assigmentService.Delete(id);

            return RedirectToAction("Details", "Project");
        }

        [HttpGet]
        public async Task<IActionResult> AssigmentDetails(Guid id)
        {
            var assigment = await _assigmentService.GetById(id);

            if (assigment == null)
                return View("Error");

            var config = new MapperConfiguration(cfg => cfg.CreateMap<Assigment, AssigmentDetailsViewModel>());
            var mapper = new Mapper(config);
            var assigmentDetailsVM = mapper.Map<AssigmentDetailsViewModel>(assigment);

            assigmentDetailsVM.ResponsibleUsers = await _assigmentService.GetAllResponisbleForTaskUsers(id);

            return View(assigmentDetailsVM);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var assigment = await _assigmentService.GetById(id);

            if(assigment == null)
                return View("Error");

            var config = new MapperConfiguration(cfg => cfg.CreateMap<Assigment, AssigmentEditViewModel>());
            var mapper = new Mapper(config);
            var assigmentEditVM = mapper.Map<AssigmentEditViewModel>(assigment);

            var users = await _userAuthenticationService.GetUsersForTaskCompliting();
            var userCheckboxes = new List<AppUserCheckBoxViewModel>();
            foreach (var user in users)
            {
                var checkbox = new AppUserCheckBoxViewModel
                {
                    IsActive = user.UserAssigments.Where(u => u.AssigmentId == id).Any(),
                    Description = $"{user.UserName} - {user.Email} ",
                    Value = user
                };

                userCheckboxes.Add(checkbox);
            }

            assigmentEditVM.ResponsibleUsersCheckboxes = userCheckboxes;

            return View(assigmentEditVM);
        }

        [HttpPost]
        public async Task<IActionResult> EditAssigment(AssigmentEditViewModel assigmentVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit assigment");
                return View("Edit", assigmentVM);
            }

            var config = new MapperConfiguration(cfg => cfg.CreateMap<AssigmentEditViewModel, Assigment>());
            var mapper = new Mapper(config);
            var assigment = mapper.Map<Assigment>(assigmentVM);

            var result = await _assigmentService.UpdateAssigmentInfo(assigment, assigmentVM.ResponsibleUsers);

            if (!result.IsSuccessful)
                TempData["Error"] = result.Message;

            return RedirectToAction("Details", "Project");
        }

        public async Task<IActionResult> DetailsUserAssigments()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var userAssigments = currentUser.UserAssigments.Select(u => u.Assigment).ToList();
            var sortedAssigments = userAssigments.SortAssigmentsByPriority();

            var config = new MapperConfiguration(cfg => cfg.CreateMap<Assigment, AssigmentDetailsViewModel>());
            var mapper = new Mapper(config);
            var assigmentDetailsVM = mapper.Map<List<AssigmentDetailsViewModel>>(sortedAssigments);

            return View(assigmentDetailsVM);
        }
    }
}

ProjectManagerWeb/ProjectManagerNew/Controllers/ProjectController.cs
using AutoMapper;
using BLL.Interfaces;
using BLL.Services;
using Core.Models;
using Core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace ProjectManager.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly IProjectService _projectService;
        private readonly UserManager<AppUser> _userManager;
        private readonly IUserAuthenticationService _userAuthenticationService;
        public ProjectController(IProjectService projectService, 
            IUserAuthenticationService userAuthenticationService,
            UserManager<AppUser> userManager)
        {
            _projectService = projectService;
            _userAuthenticationService = userAuthenticationService;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Details()
        {
            var user = await _userManager.GetUserAsync(User);
            var isAdmin = await _userManager.IsInRoleAsync(user, "Admin");

            var config = new MapperConfiguration(cfg => cfg.CreateMap<Project, ProjectDetailsViewModel>());
            var mapper = new Mapper(config);

            List<ProjectDetailsViewModel> projectsVM;
            if(isAdmin)
                projectsVM = mapper.Map<List<ProjectDetailsViewModel>>(await _projectService.GetAll());
            else
                projectsVM = mapper.Map<List<ProjectDetailsViewModel>>(await _projectService.GetUserProjects(user));
            
            return View(projectsVM);
        }

        [HttpGet]
        [Route("DetailsProject/{id}")]
        public async Task<IActionResult> DetailsProject(Guid id)
        {
            var project = await _projectService.GetById(id);

            if (project == null)
            {
                return NotFound();
            }

            var completedAssigments = await _projectService.ProgressCheck(id);
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Project, ProjectViewModel>());
            var mapper = new Mapper(config);
            var projectVM = mapper.Map<ProjectViewModel>(project);

            var allProjectUsers = await _projectService.GetAllProjectUsers(id);
            projectVM.AllProjectUsers = allProjectUsers;
            projectVM.AmountOfCompletedAssigments = completedAssigments;

            return View(projectVM);
        }

        [Authorize(Roles = "StakeHolder")]
        public async Task<IActionResult> Create()
        {
            var projectVM = new ProjectCreateViewModel();
            var users = await _userAuthenticationService.GetUsersForTaskCompliting();
            var userCheckboxes = new List<AppUserCheckBoxViewModel>();
            foreach (var user in users)
            {
                var checkbox = new AppUserCheckBoxViewModel
                {
                    IsActive = false,
                    Description = $"{user.UserName} - {user.Email} ",
                    Value = user
                };

                userCheckboxes.Add(checkbox);
            }

            projectVM.ResponsibleUsersCheckboxes = userCheckboxes;

            return View(projectVM);
        }

        [HttpPost]
        [Authorize(Roles = "StakeHolder")]
        public async Task<IActionResult> CreateProject(ProjectCreateViewModel model)
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<ProjectCreateViewModel, Project>());
            var mapper = new Mapper(config);
            var project = mapper.Map<Project>(model);
            var projectOwner = await _userAuthenticationService.GetUserById(model.ProjectOwnerId);
            project.ProjectOwner = projectOwner.Data;

            var result = await _projectService.AddProject(project);

            if(!result.IsSuccessful)
                TempData["Error"] = result.Message;

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "StakeHolder")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var project = await _projectService.GetById(id);

            if (project == null)
                return NotFound();

            var config = new MapperConfiguration(cfg => cfg.CreateMap<Project, ProjectDeleteViewModel>());
            var mapper = new Mapper(config);
            var projectVM = mapper.Map<ProjectDeleteViewModel>(project);

            return View(projectVM);
        }

        [Authorize(Roles = "StakeHolder")]
        public async Task<IActionResult> DeleteProject(Guid id)
        {
            var project = await _projectService.GetById(id);

            if (project == null)
                return NotFound();

            var result = await _projectService.DeleteProject(id);

            if (!result.IsSuccessful)
                TempData["Error"] = result.Message;

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "StakeHolder")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var project = await _projectService.GetById(id);

            if(project == null)
                return View("Error");

            var config = new MapperConfiguration(cfg => cfg.CreateMap<Project, ProjectEditViewModel>());
            var mapper = new Mapper(config);
            var projectEditVM = mapper.Map<ProjectEditViewModel>(project);

            var users = await _userAuthenticationService.GetUsersForTaskCompliting();
            var userCheckboxes = new List<AppUserCheckBoxViewModel>();
            foreach (var user in users)
            {
                var checkbox = new AppUserCheckBoxViewModel
                {
                    IsActive = user.UserProjects.Contains(project),
                    Description = $"{user.UserName} - {user.Email} ",
                    Value = user
                };

                userCheckboxes.Add(checkbox);
            }

            projectEditVM.ResponsibleUsersCheckboxes = userCheckboxes;

            return View(projectEditVM);
        }

        [HttpPost]
        [Authorize(Roles = "StakeHolder")]
        public async Task<IActionResult> EditProject(ProjectEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit assigment");
                return View("Edit", model);
            }

            var config = new MapperConfiguration(cfg => cfg.CreateMap<ProjectEditViewModel, Project>());
            var mapper = new Mapper(config);
            var project = mapper.Map<Project>(model);
            project.CurrentProjectOwnerId = model.ProjectOwnerId;
            var user = await _userAuthenticationService.GetUserById(project.CurrentProjectOwnerId);
            project.ProjectOwner = user.Data;

            var result = await _projectService.UpdateProject(project);

            if(!result.IsSuccessful)
                TempData["Error"] = result.Message;

            return RedirectToAction("Index", "Home");
        }
    }
}

ProjectManagerWeb/ProjectManagerNew/Views/Project/Create.cshtml
@using Core.ViewModels
@using Core.Models
@using Microsoft.AspNetCore.Identity

@inject UserManager<AppUser> UserManager
@model ProjectCreateViewModel

@if (TempData["Error"] != null)
{
    <div class="col-md-12 alert alert-danger">
        <span><b>Sorry!</b> - @TempData["Error"]</span>
    </div>
}
<div class="navbar-container">
</div>
<div class="main-container">
    <section class="space-sm">
        <div class="container">
            <div class="row mb-5">
                <!--end of col-->
            </div>
            <!--end of row-->
            <div class="row flex-md-row card card-md">
                <div class="card-body bg-light">
                    <div class="text-center mb-5">
                        <h1 class="h2 mb-2">Create new project</h1>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-6 col-lg-5">
                            <form method="post" asp-action="CreateProject" enctype="multipart/form-data">
                                <div class="form-row form-group">
                                    <div class="col">
                                        <input asp-for="Name" class="form-control form-control-lg" placeholder="Name" />
                                        <span asp-validation-for="Name" class="text-danger"></span>
                                    </div>
                                    <div class="col">
                                        <input asp-for="Description" class="form-control form-control-lg" placeholder="Description" />
                                        <span asp-validation-for="Description" class="text-danger"></span>
                                    </div>    
                                </div>
                                <h6>Choose project owner: </h6>

                                @foreach (var executor in Model.ResponsibleUsersCheckboxes)
                                {
                                    <div class="form-check">
                                        <input class="form-check-input"
                                               type="radio"
                                               value="@executor.Value.Id"
                                               name="ProjectOwnerId"
                                               id="checkbox_@executor.Value.Id"
                                               checked="@executor.IsActive">
                                        @{
                                            var user = await UserManager.FindByIdAsync(executor.Value.Id);
                                            var executorRole = await UserManager.GetRolesAsync(user);
                                        }
                                        <label class="form-check-label" for="checkbox_@executor.Value.Id">
                                            @executor.Description, Role: @executorRole.FirstOrDefault()
                                        </label>
                                    </div>
                                }
                                <hr />
                                <div class="form-row form-group">
                                    <div class="col">
                                        <input class="btn btn-block btn-success btn-lg" type="submit" value="Create Project" />
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--end of container-->
    </section>
    <!--end of section-->
</div>

ProjectManagerWeb/ProjectManagerNew/Views/Project/Delete.cshtml
@using Core.ViewModels
@model ProjectDeleteViewModel

<div class="container align-left">
    @if (TempData["Error"] != null)
    {
        <div class="col-md-12 alert alert-danger">
            <span><b>Sorry!</b> - @TempData["Error"]</span>
        </div>
    }
    <div class="row">
        <div class="mbr-white col-md-7 mt-4">
            <h4 class="mbr-section-title mbr-semibold pb-2 mbr-fonts-style display-4">
                Are you sure that do you want to delete project @Model.Name?
            </h4>


            <input type="radio" class="btn-check" name="options-outlined" id="danger-outlined" autocomplete="off">
            <a asp-controller="Project" asp-action="DeleteProject" asp-route-id="@Model.Id" class="btn btn-outline-danger" for="danger-outlined">
                Yes
            </a>
            <input type="radio" class="btn-check" name="options-outlined" id="success-outlined" autocomplete="off" checked>
            <a asp-controller="Home" asp-action="Index" class="btn btn-outline-success" for="success-outlined">
                No
            </a>
            
        </div>
    </div>
</div>

ProjectManagerWeb/ProjectManagerNew/Views/Project/Details.cshtml
@using Core.Models
@using Core.ViewModels
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
@model IEnumerable<ProjectDetailsViewModel>


<div class="position-relative m-5 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
        <h1 class="display-4 font-weight-normal pb-3">Available projects</h1>
        @if (User.IsInRole("StakeHolder"))
        {
            <a type="button" class="btn btn-outline-secondary" asp-controller="Project" asp-action="Create">Create new project</a>
        }        
    </div>
</div>
<div class="row">
    @foreach(var projectVM in Model)
    {
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Name: @projectVM.Name</h5>
                    
                    <p class="card-text">Description: @projectVM.Description</p>
                    <a type="button" class="btn btn-primary" asp-controller="Project" asp-action="DetailsProject" asp-route-id="@projectVM.Id">
                        View details
                    </a>
                    @if (User.IsInRole("StakeHolder"))
                    {
                        <a type="button" class="btn btn-outline-danger" asp-controller="Project" asp-action="Delete" asp-route-id="@projectVM.Id">
                            Delete project
                        </a>
                        <input type="radio" class="btn-check" name="options-outlined" id="success-outlined" autocomplete="off" checked>
                        <a asp-controller="Project" asp-action="Edit" asp-route-id="@projectVM.Id" class="btn btn-outline-success" for="success-outlined">
                            Edit
                        </a>
                    }                   
                </div>
            </div>
        </div>
    }
</div>

ProjectManagerWeb/ProjectManagerNew/Views/Project/DetailsProject.cshtml
@using Core.ViewModels
@using Core.Models
@using Microsoft.AspNetCore.Identity

@model ProjectViewModel
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

<div class="p-5 bg-light">
    <h4 class="mb-3">Project Overview</h4>
    <h1 class="mb-3">Project name: @Model.Name</h1>
    <h4 class="mb-3">Project description: @Model.Description</h4>
    @if(Model.ProjectOwner != null)
    {
        <h4 class ="mb-3">Project owner name: @Model.ProjectOwner.UserName</h4>
        <h4 class="mb-3">Project owner email: @Model.ProjectOwner.Email</h4>
    }
    <hr />
    <h4>Percentage of completed tasks: @Model.AmountOfCompletedAssigments %</h4>
    
    <br /><br />
    <h5>Tasks name: </h5>
    <ul>
        @foreach (var asssigment in Model.Assigments)
        {
            <li>@asssigment.Name</li>
        }
    </ul>
    <br /><br />
    <a type="button" class="btn btn-primary" asp-controller="Assigment" asp-action="ShowProjectTasks" asp-route-id="@Model.Id">See all project tasks</a>
    <hr/>
    @if (!User.IsInRole("Admin"))
    {
        <a type="button" class="btn btn-primary" asp-controller="Assigment" asp-action="Create" asp-route-id="@Model.Id">Add task</a>
    }   
</div>

ProjectManagerWeb/ProjectManagerNew/Views/Project/Edit.cshtml
@using Core.ViewModels
@using Core.Models
@using Microsoft.AspNetCore.Identity

@inject UserManager<AppUser> UserManager
@model ProjectEditViewModel

<div class="row m-5">
    <h1 class="text-center">Edit project page</h1>
    @if (TempData["Error"] != null)
    {
        <div class="col-md-12 alert alert-danger">
            <span><b>Sorry!</b> - @TempData["Error"]</span>
        </div>
    }
    <div class="row">
        <div class="col-md-8 offset-2">
            <form method="post" asp-action="EditProject" enctype="multipart/form-data">
                <input type="hidden" id="Id" name="Id" value="@Model.Id" />
    
    
                <div class="form-group m-2">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group m-2">
                    <label asp-for="Description">Description</label>
                    <input asp-for="Description" class="form-control" placeholder="Description">
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
    
                <h6>Choose project owner: </h6>

                @foreach (var executor in Model.ResponsibleUsersCheckboxes)
                {
                    <div class="form-check">
                        <input class="form-check-input"
                               type="radio"
                               value="@executor.Value.Id"
                               name="ProjectOwnerId"
                               id="checkbox_@executor.Value.Id"
                               checked="@executor.IsActive">
                        @{
                            var user = await UserManager.FindByIdAsync(executor.Value.Id);
                            var executorRole = await UserManager.GetRolesAsync(user);
                        }
                        <label class="form-check-label" for="checkbox_@executor.Value.Id">
                            @executor.Description, Role: @executorRole.FirstOrDefault()
                        </label>
                    </div>
                }
                <hr />

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>